# Site settings
title: 程序员阿辉
email: runphp@qq.com
description: >
  提供软件开发和技术咨询服务, PHP开发, Java开发, Go开发
baseurl: ""
url: "https://blog.runphp.net"
author: runphp
wechat: runphp
QQ: 83308224
github_username: runphp
output_ext: .html
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 50
paginate_path: /page/:num
# Build settings
markdown: kramdown
timezone: Asia/Shanghai
kramdown:
  input:          GFM
  syntax_highlighter_opts:
    default_lang: shell
fenced_code_blocks: true
exclude:
  - .idea
keep_files:
  - avatar
sass:
  load_paths: node_modules
defaults:
  -
    scope:
      path: "googledfda5ebddb0304f4.html"
    values:
      sitemap: false
  -
    scope:
        path: '_posts'
        type: posts
    values:
        layout: post
        author: runphp
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    category: :name/
    tag: :name/
