# Site settings
title: 程序员阿辉
email: runphp@qq.com
description: >
  提供软件开发和技术咨询服务, PHP开发, Java开发, Go开发
baseurl: ""
url: "https://blog.runphp.net"
author: runphp
wechat: runphp
QQ: 83308224
github_username: runphp
output_ext: .html
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 50
paginate_path: /page/:num
# Build settings
markdown: kramdown
kramdown:
  input:          GFM
fenced_code_blocks: true
exclude:
  - ".idea"
sass:
  sass_dir: _sass
  style: compressed
defaults:
  - scope:
      path: "googledfda5ebddb0304f4.html"
    values:
      sitemap: false
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category-archive
    tag: tag-archive
